steps:
  - name: step1
    when:
      event: ["commit"]
      branch: ["master"]
      skipBranch: ["development", "feature-*"]
    containerRun:
      image: busybox
      script: "echo 'Hello world!'"