steps:
  - name: step1
    containerRun:
      image: busybox
      script: "echo 'Hello world!'"

  - name: wait
    waitForAccept: {}

  - name: step2
    containerRun:
      image: busybox
      script: |
        echo "step 2"
        env